### ISSUE TITLE
CSSTricks: “Speed Up with CSS3 Gradients” uses old (but not ancient) syntax

### ISSUE THREAD

**Issue by dstorey** [dstorey/stale#12]
URL: http://css-tricks.com/css3-gradients/

Issues:
- Includes -ms- prefixed version of old syntax, which was never included in a final version
- Uses old syntax (sans "to" keyword)
- Lacks prefixless version used by IE10+ and modern browsers
- Trident (IE) section is now only for ≤IE9

Fixes:
- Remove ms prefixed version
- Add prefixless version with new syntax
- Add W3C syntax section and note that other syntaxes are only for legacy versions

There may be a more up to date article on CSS Tricks that can be pointed to instead, but the article is 3rd for "CSS Gradients" on Google, so it would be good to make clear this is outdated if going down that path. 

Contact:

GitHub: @chriscoyier

**Comment by chriscoyier** [comment]
I'll get to it as soon as I can. Within the next week for sure.

**Comment by chriscoyier** [comment]
OK I wanna be sure to get this right and cover the entire history of gradients here. Every bit of this needs fact checking. 

#### Browser totally doesn't support CSS gradients at all (IE 8-, Firefox 3.5-, Safari 3.2-, Opera 11-)

``` css
background-image: url(fallback.png);
```

Note: or `.svg` if just trying to support IE8

#### Safari 4, Chrome 1-9, iOS 3.2 - 4.3

``` css
background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#2F2727), to(#1a82f7));
```

Was there a Safari 5.0? Did it need this?

#### Safari 5.1, iOS 5.0 - 6.1, Chrome 10-???, Android 4.0 - 4.3

``` css
background-image: -webkit-linear-gradient(top, #2F2727, #1a82f7); 
```

"top" can be omitted here, but if going for left-to-right, you'd need to use "left". The "to right" stuff wasn't supported yet in these browsers.

### Firefox 3.6 - 15

``` css
background-image: -moz-linear-gradient(top, #2F2727, #1a82f7);
```

At what point did it start supporting "to right"? Not until it unprefixed? Before? After?

#### IE 9

Use filters still?

```
filter:  progid:DXImageTransform.Microsoft.gradient(startColorStr='#444444', EndColorStr='#999999'); /* IE6,IE7 */
-ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorStr='#444444', EndColorStr='#999999')"; /* IE8 */
```

Use SVG?

#### IE 10

Which syntaxes does it support? Does the "left" param work or does it need "to right"? Is there any differences between what 10 and 11 support?

#### Opera 11.1 - 11.5

Only supported linear.

``` css
background-image: -o-linear-gradient(top, #2F2727, #1a82f7);
```

#### Opera 11.6 - 12.0

Started supporting radial, still prefixed for all.

#### Opera 12.1

Unprefixed.

#### Opera 15, Chrome ???+, IE 10+, Firefox 16+, Safari 6.1+, iOS 7+, Android 4.4+

All these support the new "to" syntax, unprefixed.

``` css
background-image: linear-gradient(to right, red, yellow);
```

### So if you were going for the deepest support possible...

I guess you need three different syntaxes, various prefixes, as well as a fallback.

``` css
div {

  /* fallback/non-cover color */
  background-color: #1a82f7; 

  /* fallback image - SVG works in IE 8, otherwise do PNG */
  background-image: url(fallback-gradient.png); 

  /* Safari 4, Chrome 1-9, iOS 3.2 - 4.3 */
  background-image: -webkit-gradient(
    linear, 0% 0%, 0% 100%, 
    from(red), 
    to(orange)
  );

  /* Safari 5.1, iOS 5.0 - 6.1, Chrome 10-???, Android 4.0 - 4.3 */
  background-image: -webkit-linear-gradient(
    left,
    red,
    orange
  );

  /* Firefox 3.6 - 15 */
  background-image: -moz-linear-gradient(
    left,
    red,
    orange
  );

  /* Opera 11.1 - 12 */
  background-image: -o-linear-gradient(
    left,
    red,
    orange
  );

  /* Opera 15, Chrome ???+, IE 10+, Firefox 16+, Safari 6.1+, iOS 7+, Android 4.4+  */
  background-image: linear-gradient(
    to right,
    red,
    orange
  );

}
```

### Random Questions

How does Autoprefixer handle things? Does it output all three styles if you ask for support deep enough?

`-prefix-free` -  Is it possible that it tries to convert to a "to right" style syntax in a browser that can't handle that e.g. Safari 5.1?

Is the support the same largely for linear and radial? There is an old and new (or more) versions of that syntax and different keywords, right?

What about how color stops are handled? Was there varying versions of that?

What about repeating gradients? conical gradients?
